ayvuSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from . import views

from .users.views import UserSignUpView, UserViewSet, UserProfileViewSet
from blog.views import BlogPostViewSet
from languages.views import LanguageAPIView, language_api_view, language_detail_api_view


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'profiles', UserProfileViewSet)
router.register(r'blog', BlogPostViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    # path("api/languages/", LanguageAPIView.as_view(), name="languages"),
    path("api/languages/", language_api_view, name="languages"),
    path("api/languages/<int:pk>/", language_detail_api_view, name="languages-detail"),
    path("api/login-set-cookie/", views.login_set_cookie, name="login-cookie"),
    path("api/user-data/", views.ProfileAPIView.as_view(), name="user-data"),
    path("api/login/", views.login_view, name="login-view"),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', UserSignUpView.as_view(), name='signup'),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    #: Necessario para django-summernote
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

blog/urls.py
from django.urls import path, include
from .views import BlogPostList, BlogPostDetail, BlogPostCreate, BlogPostPreview, BlogPostSearch

app_name = 'blog'

urlpatterns = [
    path('', BlogPostList.as_view(), name='index'),
    path('add/', BlogPostCreate.as_view(), name='add_entry'),
    path('search/', BlogPostSearch.as_view(), name='search'),
    path('<slug>/', include([
        path('', BlogPostDetail.as_view(), name='post'),
        path('preview/', BlogPostPreview.as_view(), name='preview'),
    ])),
]

ayvuSite/users/models.py
from django.utils.translation import gettext_lazy as _
from django.db import models

#: custom user model
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from simple_history.models import HistoricalRecords
from languages.models import Language


class User(AbstractUser):
    """Allow for updatable User models without breaking foreign keys."""
    is_premium = models.BooleanField(_("Premium"), default=False)
    active_language = models.ForeignKey(Language, default=1, on_delete=models.SET(1))


class ProxyUser(User):
    """Custom user proxy model for digested admin management."""
    class Meta:
        verbose_name = _("Digested user")
        verbose_name_plural = _("Digested users")
        proxy = True


class UserProfile(models.Model):
    """
    Extra profile data for default users.
    """
    #: User pk as profile pk
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        primary_key=True,
        on_delete=models.CASCADE,
        related_name='user_profile',
    )
    bio = models.CharField(_("Bio"), max_length=30, blank=True)
    website = models.URLField(_("Website"), max_length=255, blank=True)
    birth_date = models.DateField(_("Birth date"), null=True, blank=True)
    speaks = models.ManyToManyField(Language, verbose_name=_("Languages spoken"), related_name='speakers')
    history = HistoricalRecords()

    def __str__(self):
        return str(self.user)

base/models.py
from django.db import models
from simple_history.models import HistoricalRecords


class BaseModel(models.Model):
    """Model definition for BaseModel."""

    status = models.BooleanField('Status', default=True)
    created_date = models.DateField('Created at', auto_now=False, auto_now_add=True)
    modified_date = models.DateField('Modified at', auto_now=True, auto_now_add=False)
    deleted_date = models.DateField('Deleted at', auto_now=True, auto_now_add=False)
    history = HistoricalRecords(inherit=True)

    # @property
    # def _history_user(self):
    #     return self.changed_by
    #
    # @_history_user.setter
    # def _history_user(self, value):
    #     self.changed_by = value

    class Meta:
        abstract = True

ayvuSite/users/forms.py
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django import forms

from languages.models import Language
from .models import User, UserProfile


class UserSignUpForm(UserCreationForm):
    speaks = forms.ModelMultipleChoiceField(
        queryset=Language.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label=_("Languages spoken"),
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_premium = False
        user.save()
        profile = UserProfile.objects.create(user=user)
        profile.speaks.add(*self.cleaned_data.get('speaks'))
        return user

ayvuSite/users/views.py
from django.contrib.auth import get_user_model, login
from django.shortcuts import redirect
from django.views.generic import CreateView
from rest_framework import viewsets, permissions

from .serializers import UserSerializer, UserProfileSerializer
from .forms import UserSignUpForm
from .models import UserProfile

User = get_user_model()


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    lookup_field = 'username'


class UserProfileViewSet(viewsets.ModelViewSet):
    queryset = UserProfile.objects.all().order_by('-user')
    serializer_class = UserProfileSerializer


# Regular HTML template views:
# ------------------------------
class UserSignUpView(CreateView):
    model = User
    form_class = UserSignUpForm
    template_name = 'registration/signup.html'

    def get_context_data(self, **kwargs):
        kwargs['is_premium'] = False
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')

ayvuSite/views.py
import json

from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import require_POST
from django.contrib.auth import authenticate, login
from django.http import JsonResponse
from django.shortcuts import render
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.views import APIView
from .users.serializers import UserSerializer


# Create your views here.
class ProfileAPIView(APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, format=None):
        user = request.user
        serialized_user = UserSerializer(user)
        return Response(serialized_user.data)


@ensure_csrf_cookie
def login_set_cookie(request):
    """
    `login_view` requires that a csrf cookie be set.
    `getCsrfToken` in `auth.js` uses this cookie to
    make a request to `login_view`
    """
    return JsonResponse({"details": "CSRF cookie set"})


@require_POST
def login_view(request):
    """
    This function logs in the user and returns
    an HttpOnly cookie, the `sessionid` cookie
    """
    print(request.user)
    print(request.headers)
    print(request.body)
    if request.user.is_authenticated:
        return JsonResponse({"detail": "Success"})

    data = json.loads(request.body)
    username = data.get("username")
    password = data.get("password")
    if username is None or password is None:
        return JsonResponse(
            {"errors": {"__all__": "Please enter both username and password"}},
            status=400,
        )
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return JsonResponse({"detail": "Success"})
    return JsonResponse({"detail": "Invalid credentials"}, status=400)


def home(request):
    return render(request, 'home.html')

base/views.py
from django.shortcuts import render

# Create your views here.

ayvuSite/templates/_messages.html
{% if messages %}
    {% for message in messages %}
        <div class="row">
            <div class="col s12 m12">
                <div class="card-panel {{ message.tags }}">
                    <span class="">
                        {{ message }}
                    </span>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}

ayvuSite/templates/_navbar.html
{% load static %}
<nav>
    <div class="nav-wrapper blue-grey">
        <a href="{% url 'home' %}" class="brand-logo">&nbsp; Ayvu</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'blog:index' %}">Blog</a></li>
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Signup</a></li>
        </ul>
    </div>
</nav>

ayvuSite/templates/_searchbar.html
<div class="row">
    <div class="col s12">
        <div class="row">
            <form method="get" action="{% url 'blog:search' %}">
                <div class="input-field col s12">
                    <i class="material-icons prefix" aria-hidden="true">search</i>
                    <input type="text" id="autocomplete-input" class="autocomplete"
                           name="q"
                           value="{{ request.GET.q }}"
                    />
                    <label for="autocomplete-input">Search...</label>
                </div>
                {% include '_messages.html' %}
            </form>
        </div>
    </div>
</div>

ayvuSite/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Import style.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>{% block title %}Home{% endblock title %} | Ayvu</title>
</head>

<body>

{% include '_navbar.html' %}

<div class="container">

    {% if 'accounts' not in request.path %}
        {% include '_searchbar.html' %}
    {% endif %}

    {% block content %}{% endblock content %}

    <!--JavaScript at end of body for optimized loading-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</div>
</body>
</html>

ayvuSite/templates/home.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
<h4>My home page.</h4>
{% endblock content %}